CREATE TABLE IF NOT EXISTS lab_mind_document_parent_block (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    task_id BIGINT NOT NULL COMMENT '索引任务id',
    plan_id BIGINT DEFAULT NULL COMMENT '策略方案id',
    parent_no INT NOT NULL COMMENT '父块序号',
    source_type TINYINT NOT NULL DEFAULT '1' COMMENT '内容来源 1:原文切块 2:后处理补全文本',
    section_path VARCHAR(1000) DEFAULT NULL COMMENT '章节路径',
    structure_node_id BIGINT DEFAULT NULL COMMENT '关联的结构节点id',
    structure_node_type TINYINT DEFAULT NULL COMMENT '关联的结构节点类型',
    canonical_path VARCHAR(1000) DEFAULT NULL COMMENT '结构节点稳定路径',
    item_index INT DEFAULT NULL COMMENT '列表项/步骤项序号',
    parent_text LONGTEXT COMMENT '父块完整内容',
    char_count INT DEFAULT '0' COMMENT '字符数',
    token_count INT DEFAULT '0' COMMENT 'token数',
    child_count INT DEFAULT '0' COMMENT '父块内部child数量',
    start_chunk_no INT DEFAULT NULL COMMENT '父块映射到的第一个child序号',
    end_chunk_no INT DEFAULT NULL COMMENT '父块映射到的最后一个child序号',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_parent_no (task_id, parent_no),
    KEY idx_document_id (document_id),
    KEY idx_task_id (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档父块表';

CREATE TABLE IF NOT EXISTS lab_mind_document_chunk (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    task_id BIGINT NOT NULL COMMENT '索引任务id',
    plan_id BIGINT DEFAULT NULL COMMENT '策略方案id',
    parent_block_id BIGINT NOT NULL COMMENT '所属父块id',
    chunk_no INT NOT NULL COMMENT '块序号',
    source_type TINYINT NOT NULL DEFAULT '1' COMMENT '内容来源 1:原文切块 2:后处理补全文本',
    section_path VARCHAR(1000) DEFAULT NULL COMMENT '章节路径',
    structure_node_id BIGINT DEFAULT NULL COMMENT '关联的结构节点id',
    structure_node_type TINYINT DEFAULT NULL COMMENT '关联的结构节点类型',
    canonical_path VARCHAR(1000) DEFAULT NULL COMMENT '结构节点稳定路径',
    item_index INT DEFAULT NULL COMMENT '列表项/步骤项序号',
    chunk_text LONGTEXT COMMENT '切块内容',
    char_count INT DEFAULT '0' COMMENT '字符数',
    token_count INT DEFAULT '0' COMMENT 'token数',
    vector_status TINYINT NOT NULL DEFAULT '1' COMMENT '向量状态 1:待向量化 2:向量化中 3:向量化成功 4:向量化失败',
    vector_store_type TINYINT NOT NULL DEFAULT '2' COMMENT '向量库类型 1:Milvus 2:PGVector 3:Elasticsearch',
    vector_id VARCHAR(128) DEFAULT NULL COMMENT '向量库主键',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_chunk_no (task_id, chunk_no),
    KEY idx_document_id (document_id),
    KEY idx_parent_block_id (parent_block_id),
    KEY idx_vector_status (vector_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档切块表';
