-- lab-mind-business-chat 文档域建表脚本
CREATE TABLE IF NOT EXISTS lab_mind_document (
    id BIGINT NOT NULL COMMENT '主键id',
    document_name VARCHAR(255) NOT NULL COMMENT '文档名称',
    workspace_id VARCHAR(64) NOT NULL COMMENT '所属工作组id',
    original_file_name VARCHAR(255) NOT NULL COMMENT '原始文件名',
    file_type TINYINT NOT NULL COMMENT '文件类型 1:PDF 2:DOC 3:DOCX 4:TXT 5:MD 6:HTML 7:PPT 8:PPTX',
    mime_type VARCHAR(128) DEFAULT NULL COMMENT 'MIME类型',
    file_size BIGINT DEFAULT '0' COMMENT '文件大小(byte)',
    storage_type TINYINT NOT NULL DEFAULT '1' COMMENT '存储类型 1:MinIO',
    bucket_name VARCHAR(128) DEFAULT NULL COMMENT 'bucket名称',
    object_name VARCHAR(512) DEFAULT NULL COMMENT '对象名称',
    object_url VARCHAR(1024) DEFAULT NULL COMMENT '文件访问地址',
    parse_status TINYINT NOT NULL DEFAULT '1' COMMENT '解析状态 1:待解析 2:解析中 3:解析成功 4:解析失败',
    strategy_status TINYINT NOT NULL DEFAULT '1' COMMENT '策略状态 1:待推荐 2:已推荐 3:已确认 4:已失效',
    index_status TINYINT NOT NULL DEFAULT '1' COMMENT '索引状态 1:待构建 2:构建中 3:构建成功 4:构建失败',
    char_count INT DEFAULT '0' COMMENT '解析后字符数',
    token_count INT DEFAULT '0' COMMENT '解析后token估算数',
    structure_level TINYINT DEFAULT '0' COMMENT '结构化程度 0:未知 1:低 2:中 3:高',
    content_quality_level TINYINT DEFAULT '0' COMMENT '内容质量 0:未知 1:低 2:中 3:高',
    parse_text_path VARCHAR(512) DEFAULT NULL COMMENT '解析文本存储路径',
    parse_error_msg VARCHAR(1000) DEFAULT NULL COMMENT '解析失败原因',
    knowledge_scope_code VARCHAR(64) DEFAULT NULL COMMENT '业务知识域编码，例如 oa / crm / finance',
    knowledge_scope_name VARCHAR(128) DEFAULT NULL COMMENT '业务知识域名称，例如 OA系统 / CRM系统',
    business_category VARCHAR(128) DEFAULT NULL COMMENT '业务分类，例如 流程 / 规则 / 操作手册',
    document_tags VARCHAR(512) DEFAULT NULL COMMENT '逗号分隔标签快照',
    current_plan_id BIGINT DEFAULT NULL COMMENT '当前策略方案id',
    last_parse_task_id BIGINT DEFAULT NULL COMMENT '最近一次成功解析任务id',
    structure_node_count INT DEFAULT '0' COMMENT '最近一次结构化解析生成的节点数',
    last_index_task_id BIGINT DEFAULT NULL COMMENT '最近一次索引任务id',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_document_workspace (workspace_id, status, create_time),
    KEY idx_object_name (object_name),
    KEY idx_parse_status (parse_status),
    KEY idx_strategy_status (strategy_status),
    KEY idx_index_status (index_status),
    KEY idx_knowledge_scope_code (knowledge_scope_code),
    KEY idx_current_plan_id (current_plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档表';

CREATE TABLE IF NOT EXISTS lab_mind_document_strategy_plan (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    plan_version INT NOT NULL DEFAULT '1' COMMENT '方案版本号',
    plan_source TINYINT NOT NULL DEFAULT '1' COMMENT '方案来源 1:系统推荐 2:用户调整',
    plan_status TINYINT NOT NULL DEFAULT '1' COMMENT '方案状态 1:待确认 2:已确认 3:已执行 4:已废弃',
    strategy_count TINYINT NOT NULL DEFAULT '0' COMMENT '策略数量',
    strategy_snapshot VARCHAR(255) DEFAULT NULL COMMENT '策略快照，例:1,2,3',
    recommend_reason TEXT COMMENT '推荐原因',
    adjust_note VARCHAR(500) DEFAULT NULL COMMENT '调整说明',
    confirm_user_id BIGINT DEFAULT NULL COMMENT '确认人id',
    confirm_time DATETIME DEFAULT NULL COMMENT '确认时间',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_version (document_id, plan_version),
    KEY idx_plan_status (plan_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档策略方案表';

CREATE TABLE IF NOT EXISTS lab_mind_document_strategy_step (
    id BIGINT NOT NULL COMMENT '主键id',
    plan_id BIGINT NOT NULL COMMENT '方案id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    step_no INT NOT NULL COMMENT '执行顺序',
    pipeline_type VARCHAR(16) NOT NULL COMMENT '流水线类型 PARENT:父块流水线 CHILD:子块流水线',
    strategy_type TINYINT NOT NULL COMMENT '策略类型 1:基于文档结构切块 2:递归分块 3:语义分块 4:大模型智能切块',
    strategy_role TINYINT NOT NULL DEFAULT '1' COMMENT '策略角色 1:主策略 2:优化策略 3:兜底策略 4:增强策略',
    source_type TINYINT NOT NULL DEFAULT '1' COMMENT '来源类型 1:系统推荐 2:用户新增 3:用户保留',
    execute_status TINYINT NOT NULL DEFAULT '1' COMMENT '执行状态 1:待执行 2:执行中 3:执行成功 4:执行失败 5:已跳过',
    recommend_reason VARCHAR(500) DEFAULT NULL COMMENT '本步骤推荐原因',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_plan_pipeline_step_no (plan_id, pipeline_type, step_no),
    KEY idx_document_id (document_id),
    KEY idx_strategy_type (strategy_type),
    KEY idx_pipeline_type (pipeline_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档策略步骤表';

CREATE TABLE IF NOT EXISTS lab_mind_document_task (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    plan_id BIGINT DEFAULT NULL COMMENT '执行方案id',
    task_type TINYINT NOT NULL COMMENT '任务类型 1:解析路由 2:构建索引',
    task_status TINYINT NOT NULL DEFAULT '1' COMMENT '任务状态 1:新建 2:进行中 3:成功 4:失败 5:已取消',
    current_stage TINYINT NOT NULL DEFAULT '1' COMMENT '当前阶段 1:文件上传 2:内容解析 3:策略路由 4:策略确认 5:切块执行 6:切块后处理 7:向量化 8:入库完成',
    trigger_source TINYINT NOT NULL DEFAULT '1' COMMENT '触发来源 1:系统自动 2:用户手动',
    strategy_snapshot VARCHAR(255) DEFAULT NULL COMMENT '执行时策略快照，例:1,2,3',
    retry_count INT NOT NULL DEFAULT '0' COMMENT '重试次数',
    start_time DATETIME DEFAULT NULL COMMENT '开始时间',
    finish_time DATETIME DEFAULT NULL COMMENT '结束时间',
    cost_millis BIGINT DEFAULT '0' COMMENT '耗时毫秒',
    error_code VARCHAR(64) DEFAULT NULL COMMENT '错误码',
    error_msg VARCHAR(1000) DEFAULT NULL COMMENT '错误信息',
    ext_json TEXT COMMENT '扩展信息JSON',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_document_task (document_id, task_type),
    KEY idx_task_status (task_status),
    KEY idx_plan_id (plan_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档任务表';

CREATE TABLE IF NOT EXISTS lab_mind_document_task_log (
    id BIGINT NOT NULL COMMENT '主键id',
    task_id BIGINT NOT NULL COMMENT '任务id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    stage_type TINYINT NOT NULL COMMENT '阶段类型 1:文件上传 2:内容解析 3:策略路由 4:策略确认 5:切块执行 6:切块后处理 7:向量化 8:入库完成',
    event_type TINYINT NOT NULL COMMENT '事件类型 1:开始 2:完成 3:失败 4:推荐策略 5:用户调整 6:用户确认',
    log_level TINYINT NOT NULL DEFAULT '1' COMMENT '日志级别 1:INFO 2:WARN 3:ERROR',
    operator_type TINYINT NOT NULL DEFAULT '1' COMMENT '操作人类型 1:系统 2:用户 3:管理员',
    operator_id BIGINT DEFAULT NULL COMMENT '操作人id',
    content VARCHAR(1000) DEFAULT NULL COMMENT '日志内容',
    detail_json TEXT COMMENT '日志明细JSON',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_task_id (task_id),
    KEY idx_document_id (document_id),
    KEY idx_stage_type (stage_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档任务日志表';

CREATE TABLE IF NOT EXISTS lab_mind_document_structure_node (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    parse_task_id BIGINT NOT NULL COMMENT '解析任务id',
    node_no INT NOT NULL COMMENT '当前文档内的稳定顺序号',
    node_type TINYINT NOT NULL COMMENT '节点类型 1:文档根节点 2:章节节点 3:步骤节点 4:列表项节点',
    parent_node_id BIGINT DEFAULT NULL COMMENT '父节点id',
    prev_sibling_node_id BIGINT DEFAULT NULL COMMENT '上一个同级节点id',
    next_sibling_node_id BIGINT DEFAULT NULL COMMENT '下一个同级节点id',
    depth INT NOT NULL DEFAULT '0' COMMENT '节点深度',
    node_code VARCHAR(128) DEFAULT NULL COMMENT '节点编码，例如 1.2 / 第一章 / 4',
    title VARCHAR(1000) DEFAULT NULL COMMENT '节点标题',
    anchor_text VARCHAR(1000) DEFAULT NULL COMMENT '供导航和锚点使用的短锚文本',
    canonical_path VARCHAR(1000) DEFAULT NULL COMMENT '节点稳定路径',
    section_path VARCHAR(1000) DEFAULT NULL COMMENT '兼容现有系统的章节路径文本',
    content_text LONGTEXT COMMENT '节点正文',
    item_index INT DEFAULT NULL COMMENT '列表项/步骤项序号',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_parse_task_node_no (parse_task_id, node_no),
    KEY idx_document_id (document_id),
    KEY idx_parse_task_id (parse_task_id),
    KEY idx_parent_node_id (parent_node_id),
    KEY idx_node_type (node_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档结构节点表';

CREATE TABLE IF NOT EXISTS lab_mind_document_parent_block (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    workspace_id VARCHAR(64) NOT NULL COMMENT '所属工作组id',
    task_id BIGINT NOT NULL COMMENT '索引任务id',
    plan_id BIGINT DEFAULT NULL COMMENT '策略方案id',
    parent_no INT NOT NULL COMMENT '父块序号',
    source_type TINYINT NOT NULL DEFAULT '1' COMMENT '内容来源 1:原文切块 2:后处理补全文本',
    section_path VARCHAR(1000) DEFAULT NULL COMMENT '章节路径',
    structure_node_id BIGINT DEFAULT NULL COMMENT '关联的结构节点id',
    structure_node_type TINYINT DEFAULT NULL COMMENT '关联的结构节点类型',
    canonical_path VARCHAR(1000) DEFAULT NULL COMMENT '结构节点稳定路径',
    item_index INT DEFAULT NULL COMMENT '列表项/步骤项序号',
    parent_text LONGTEXT COMMENT '父块完整内容',
    char_count INT DEFAULT '0' COMMENT '字符数',
    token_count INT DEFAULT '0' COMMENT 'token数',
    child_count INT DEFAULT '0' COMMENT '父块内部child数量',
    start_chunk_no INT DEFAULT NULL COMMENT '父块映射到的第一个child序号',
    end_chunk_no INT DEFAULT NULL COMMENT '父块映射到的最后一个child序号',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_parent_no (task_id, parent_no),
    KEY idx_parent_workspace (workspace_id, document_id),
    KEY idx_document_id (document_id),
    KEY idx_task_id (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档父块表';

CREATE TABLE IF NOT EXISTS lab_mind_document_chunk (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    workspace_id VARCHAR(64) NOT NULL COMMENT '所属工作组id',
    task_id BIGINT NOT NULL COMMENT '索引任务id',
    plan_id BIGINT DEFAULT NULL COMMENT '策略方案id',
    parent_block_id BIGINT NOT NULL COMMENT '所属父块id',
    chunk_no INT NOT NULL COMMENT '块序号',
    source_type TINYINT NOT NULL DEFAULT '1' COMMENT '内容来源 1:原文切块 2:后处理补全文本',
    section_path VARCHAR(1000) DEFAULT NULL COMMENT '章节路径',
    structure_node_id BIGINT DEFAULT NULL COMMENT '关联的结构节点id',
    structure_node_type TINYINT DEFAULT NULL COMMENT '关联的结构节点类型',
    canonical_path VARCHAR(1000) DEFAULT NULL COMMENT '结构节点稳定路径',
    item_index INT DEFAULT NULL COMMENT '列表项/步骤项序号',
    chunk_text LONGTEXT COMMENT '切块内容',
    char_count INT DEFAULT '0' COMMENT '字符数',
    token_count INT DEFAULT '0' COMMENT 'token数',
    vector_status TINYINT NOT NULL DEFAULT '1' COMMENT '向量状态 1:待向量化 2:向量化中 3:向量化成功 4:向量化失败',
    vector_store_type TINYINT NOT NULL DEFAULT '1' COMMENT '向量库类型 1:Milvus 2:PGVector 3:Elasticsearch',
    vector_id VARCHAR(128) DEFAULT NULL COMMENT '向量库主键',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_task_chunk_no (task_id, chunk_no),
    KEY idx_chunk_workspace (workspace_id, document_id),
    KEY idx_document_id (document_id),
    KEY idx_parent_block_id (parent_block_id),
    KEY idx_vector_status (vector_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='文档切块表';
