-- lab-mind-business-chat 知识路由资产补充表
CREATE TABLE IF NOT EXISTS lab_mind_knowledge_document_profile (
    id BIGINT NOT NULL COMMENT '主键id',
    document_id BIGINT NOT NULL COMMENT '文档id',
    workspace_id VARCHAR(64) NOT NULL COMMENT '所属工作组id',
    scope_code VARCHAR(64) NOT NULL COMMENT '知识范围编码',
    topic_code VARCHAR(64) NOT NULL COMMENT '知识专题编码',
    profile_status TINYINT NOT NULL DEFAULT '1' COMMENT '画像状态 1:已生成 2:已失效',
    summary_text VARCHAR(2000) NOT NULL COMMENT '文档路由摘要',
    answerable_questions_json JSON NOT NULL COMMENT '可回答问题JSON数组',
    unanswerable_questions_json JSON NOT NULL COMMENT '不可回答问题JSON数组',
    business_entities_json JSON NOT NULL COMMENT '业务实体JSON数组',
    terms_json JSON NOT NULL COMMENT '术语JSON数组',
    question_patterns_json JSON NOT NULL COMMENT '问题模式JSON数组',
    profile_version INT NOT NULL DEFAULT '1' COMMENT '画像版本',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_document_profile (document_id, profile_version),
    KEY idx_profile_workspace (workspace_id, document_id, status),
    KEY idx_scope_topic (scope_code, topic_code),
    KEY idx_profile_status (profile_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识文档画像表';

CREATE TABLE IF NOT EXISTS lab_mind_knowledge_route_trace (
    id BIGINT NOT NULL COMMENT '主键id',
    trace_id VARCHAR(64) NOT NULL COMMENT '路由追踪编号',
    workspace_id VARCHAR(64) NOT NULL COMMENT '所属工作组id',
    conversation_id VARCHAR(64) COLLATE utf8mb4_bin DEFAULT NULL COMMENT '会话编号',
    exchange_id BIGINT DEFAULT NULL COMMENT '轮次id',
    question TEXT NOT NULL COMMENT '原始问题',
    rewritten_question TEXT DEFAULT NULL COMMENT '改写问题',
    intent_type VARCHAR(64) DEFAULT NULL COMMENT '意图类型',
    selected_scope_code VARCHAR(64) DEFAULT NULL COMMENT '选中知识范围',
    selected_topic_code VARCHAR(64) DEFAULT NULL COMMENT '选中知识专题',
    selected_document_ids JSON NOT NULL COMMENT '选中文档id列表',
    route_result_json JSON NOT NULL COMMENT '路由结果快照',
    user_selected_document_id BIGINT DEFAULT NULL COMMENT '用户手动选择的文档id，影子路由使用',
    route_top_document_id BIGINT DEFAULT NULL COMMENT '路由第一名文档id',
    hit_selected_document TINYINT DEFAULT NULL COMMENT '影子路由是否命中用户手动选择 1:命中 0:未命中',
    confidence DECIMAL(10, 6) NOT NULL DEFAULT '0.000000' COMMENT '路由置信度',
    route_status VARCHAR(32) NOT NULL DEFAULT 'FAILED' COMMENT '路由状态 SUCCESS/LOW_CONFIDENCE/FAILED',
    route_mode VARCHAR(32) NOT NULL DEFAULT 'AUTO' COMMENT '路由模式 AUTO/SHADOW',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    UNIQUE KEY uk_trace_id (trace_id),
    KEY idx_route_trace_workspace (workspace_id, status, create_time),
    KEY idx_conversation_exchange (conversation_id, exchange_id),
    KEY idx_scope_topic (selected_scope_code, selected_topic_code),
    KEY idx_route_status (route_status),
    KEY idx_shadow_hit (route_mode, hit_selected_document)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识路由追踪表';

CREATE TABLE IF NOT EXISTS lab_mind_knowledge_route_trace_candidate (
    id BIGINT NOT NULL COMMENT '主键id',
    trace_id VARCHAR(64) NOT NULL COMMENT '路由追踪编号',
    candidate_type VARCHAR(32) NOT NULL COMMENT '候选类型 SCOPE/TOPIC/DOCUMENT',
    candidate_id VARCHAR(64) NOT NULL COMMENT '候选id或编码',
    candidate_name VARCHAR(255) NOT NULL COMMENT '候选名称',
    score DECIMAL(10, 4) NOT NULL DEFAULT '0.0000' COMMENT '候选得分',
    hit_reason VARCHAR(1000) NOT NULL COMMENT '命中原因',
    rank_no INT NOT NULL COMMENT '排序',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    edit_time DATETIME DEFAULT NULL COMMENT '编辑时间',
    status TINYINT(1) DEFAULT '1' COMMENT '1:正常 0:删除',
    PRIMARY KEY (id),
    KEY idx_trace_rank (trace_id, rank_no),
    KEY idx_candidate (candidate_type, candidate_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='知识路由候选明细表';
