<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.labmind</groupId>
        <artifactId>lab-mind-redisson-framework</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>lab-mind-redisson-service-framework</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>lab-mind-redisson-common-framework</module>
        <module>lab-mind-redisson-repeat-execute-limit-framework</module>
        <module>lab-mind-redisson-service-lease-framework</module>
        <module>lab-mind-redisson-service-lock-framework</module>
    </modules>
</project>
